#pragma once
#ifndef _WEB_FORM_MAP_H
#define _WEB_FORM_MAP_H

#define WF_FRAME_LEN "frameLen"
#define WF_FORCED_TRIGGER "forcedTrigger"
#define WF_SYNC_BANG "syncBang"
#define WF_REAL_TIME "realTime"
#define WF_REG_NUM "regNum"
#define WF_DATA_IN "dataIn"
#define WF_CHANNEL_NUM "channelNum"
#define WF_FRAME_NUM "frameNum"
#define WF_DATA_OUT "dataOut"
#define WF_STATUS "status"
#define WF_STARTUP_CONFIG_MODE "startupConfigMode"

#define STARTUP_MODE_NO_TRG "no_trg"
#define STARTUP_MODE_AUTO_TRG "auto_trg"

#define WF_GLIMIT_1 "gLimit1"
#define WF_GLIMIT_2 "gLimit2"
#define WF_GLIMIT_3 "gLimit3"
#define WF_GLIMIT_4 "gLimit4"
#define WF_GLIMIT_5 "gLimit5"
#define WF_GLIMIT_6 "gLimit6"
#define WF_GLIMIT_7 "gLimit7"
#define WF_GLIMIT_8 "gLimit8"

#define WF_LLIMIT_11 "LTHR11"
#define WF_LLIMIT_12 "LTHR12"
#define WF_LLIMIT_21 "LTHR21"
#define WF_LLIMIT_22 "LTHR22"
#define WF_LLIMIT_31 "LTHR31"
#define WF_LLIMIT_32 "LTHR32"
#define WF_LLIMIT_33 "LTHR33"
#define WF_LLIMIT_34 "LTHR34"
#define WF_LLIMIT_41 "LTHR41"
#define WF_LLIMIT_42 "LTHR42"
#define WF_LLIMIT_43 "LTHR43"
#define WF_LLIMIT_44 "LTHR44"
#define WF_LLIMIT_51 "LTHR51"
#define WF_LLIMIT_52 "LTHR52"
#define WF_LLIMIT_61 "LTHR61"
#define WF_LLIMIT_62 "LTHR62"
#define WF_LLIMIT_71 "LTHR71"
#define WF_LLIMIT_72 "LTHR72"
#define WF_LLIMIT_73 "LTHR73"
#define WF_LLIMIT_74 "LTHR74"
#define WF_LLIMIT_81 "LTHR81"
#define WF_LLIMIT_82 "LTHR82"
#define WF_LLIMIT_83 "LTHR83"
#define WF_LLIMIT_84 "LTHR84"

#define WF_CHIP_NUM "chipSelect"
#endif
